import * as dotenv from 'dotenv';

const isProduction = () => process.env.NODE_ENV === 'production';

const isDevelopment = () => process.env.NODE_ENV === 'development';

const isTest = () => process.env.NODE_ENV === 'test';

const isLocalDevelopment = () => process.env.NODE_ENV !== 'production' && process.env.NODE_ENV !== 'test';

if (!isProduction()) {
  dotenv.config();
}

const {
  API_SHOWS_REAL_ERRORS,
  APP_DEV_URL,
  API_DEV_URL,
  API_URL,
  APP_URL,
  AWS_S3_BUCKET_NAME,
  STRIPE_DEV_CONNECT_CLIENT_ID,
  STRIPE_CONNECT_CLIENT_ID,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  FACEBOOK_DEV_APP_ID,
  FACEBOOK_DEV_APP_SECRET,
  FB_MESSAGING_VERIFY_TOKEN,
  JWT_SECRET,
  NODE_ENV,
  PORT,
  REDIS_ADDRESS_DEV,
  REDIS_ADDRESS_INT,
  REDIS_PORT,
  SHOW_API_DOCUMENTATION,
  AWS_S3_ACCESS_KEY_ID,
  AWS_S3_SECRET_ACCESS_KEY,
  AWS_S3_REGION,
  AWS_CLOUDWATCH_REGION,
  AWS_CLOUDWATCH_ACCESS_KEY_ID,
  AWS_CLOUDWATCH_SECRET_ACCESS_KEY,
  // DB_LOGGING,
  REGISTRATION_SECRET,
  SENDGRID_API_KEY,
  SENDGRID_TEMPLATE_NEW_ACCOUNT,
  SENDGRID_TEMPLATE_FORGOT_PASSWORD,
  STRIPE_API_KEY,
  STRIPE_DEV_API_KEY,
  TRACK_URL,
  TRACK_DEV_URL,
} = process.env;

export const environment = {
  TRACK_URL: isProduction() ? TRACK_URL : TRACK_DEV_URL,
  API_URL: isProduction() ? API_URL : API_DEV_URL,
  API_SHOWS_REAL_ERRORS,
  APP_URL: isProduction() ? APP_URL : APP_DEV_URL,
  AWS_CLOUDWATCH_ACCESS_KEY_ID,
  AWS_CLOUDWATCH_REGION,
  AWS_CLOUDWATCH_SECRET_ACCESS_KEY,
  AWS_S3_ACCESS_KEY_ID,
  AWS_S3_BUCKET_NAME,
  AWS_S3_REGION,
  AWS_S3_SECRET_ACCESS_KEY,
  DB_LOGGING: 'true',
  FACEBOOK_APP_ID: isProduction() ? FACEBOOK_APP_ID : FACEBOOK_DEV_APP_ID,
  FACEBOOK_APP_SECRET: isProduction() ? FACEBOOK_APP_SECRET : FACEBOOK_DEV_APP_SECRET,
  FB_MESSAGING_VERIFY_TOKEN,
  JWT_SECRET,
  NODE_ENV,
  PORT,
  REDIS_ADDRESS: isProduction() ? REDIS_ADDRESS_INT : REDIS_ADDRESS_DEV,
  REDIS_PORT,
  REGISTRATION_SECRET,
  SENDGRID_API_KEY,
  SENDGRID_TEMPLATE_FORGOT_PASSWORD,
  SENDGRID_TEMPLATE_NEW_ACCOUNT,
  SHOW_API_DOCUMENTATION,
  STRIPE_API_SECRET_KEY: isProduction() ? STRIPE_API_KEY : STRIPE_DEV_API_KEY,
  STRIPE_CONNECT_CLIENT_ID: isProduction() ? STRIPE_CONNECT_CLIENT_ID : STRIPE_DEV_CONNECT_CLIENT_ID,
  isDevelopment,
  isLocalDevelopment,
  isProduction,
  isTest,
};
